spring.application.name=registration-service

server.port=${REGISTRATION_SERVICE_PORT:8083}

spring.config.import=optional:file:./.env[.properties],optional:file:../.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/registration_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

course-service.base-url=${COURSE_SERVICE_BASE_URL:http://localhost:8082}
jwt.secret=${JWT_SECRET:CRS-Microservices-Secret-Key-Nam-4-Hoc-Ky-2026-Doi-Trong-Thuc-Te}
